services:
  - type: web
    name: voltfusion-hess
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
